#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

# config
bspc config border_width 0
bspc config window_gap 10
bspc config split_ratio 0.51
bspc config borderless_monocle true
bspc config gapless_monocle false


bspc config swallow_first_click true
bspc config focus_follows_pointer true

bspc config normal_border_color "#282828"
bspc config active_border_color "#abacdb"
bspc config focused_border_color "#8da1ea"
bspc config presel_feedback_color "#8da1ea"

# Window rules
bspc rule -a mpv state=floating
bspc rule -a Emacs state=tiled

# wmname LG3D &
xsetroot -cursor_name left_ptr &

./.config/polybar/launch.sh
